In [66]:
import numpy as np
import scipy.special
sigmoid_function = lambda x : scipy.special.expit(x)


In [67]:
epochs = 700

input = np.asarray([[0.9, 0.1, 0.8]]).T
target = np.asarray([[0.6, 0.8, 0.5]]).T

weight_input_layer1 = np.asarray(
    [
        [0.9, 0.3, 0.4],
        [0.2, 0.8, 0.2],
        [0.1, 0.5, 0.6]
    ]
)
print(weight_input_layer1)
print("============")

weight_layer1_layer2 = np.asarray([
    [0.3, 0.7, 0.5],
    [0.6, 0.5, 0.2],
    [0.8, 0.1, 0.9]

])

print(weight_layer1_layer2)




[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


학습 전 결과

In [68]:
# 순전파
input_layer1 = np.dot(weight_input_layer1, input)
input_layer1_sig = sigmoid_function(input_layer1)
layer1_layer2 = np.dot(weight_layer1_layer2, input_layer1_sig)
layer1_layer2_sig = sigmoid_function(layer1_layer2)

print("before result : \n", layer1_layer2_sig)


print("======")
print("input_layer1_weight")
print(weight_input_layer1)

print("=====")
print("layer1_layer2_weight")
print(weight_layer1_layer2)

before result : 
 [[0.72630335]
 [0.70859807]
 [0.77809706]]
input_layer1_weight
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
=====
layer1_layer2_weight
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]


학습 시작


0.1 => learningRate

In [69]:

print("start Training")

for i in range(epochs):
  # 순전파
  input_layer1 = np.dot(weight_input_layer1, input)
  input_layer1_sig = sigmoid_function(input_layer1)
  layer1_layer2 = np.dot(weight_layer1_layer2, input_layer1_sig)
  layer1_layer2_sig = sigmoid_function(layer1_layer2)

  # 역전파
  layer1_layer2_err = target - layer1_layer2_sig
  input_layer1_err = np.dot(weight_layer1_layer2.T, layer1_layer2_err)
  weight_layer1_layer2 += 0.1 * np.dot(layer1_layer2_err * layer1_layer2_sig * (1 - layer1_layer2_sig), input_layer1_sig.T)
  weight_input_layer1 += 0.1 * np.dot(input_layer1_err * input_layer1_sig * (1 - input_layer1_sig), input.T)

print("finish Training")

start Training
finish Training


학습 완료 후 결과 추출

In [70]:
# 순전파
input_layer1 = np.dot(weight_input_layer1, input)
input_layer1_sig = sigmoid_function(input_layer1)
layer1_layer2 = np.dot(weight_layer1_layer2, input_layer1_sig)
layer1_layer2_sig = sigmoid_function(layer1_layer2)

print("after result : \n", layer1_layer2_sig)


print("======")
print("input_layer1_weight")
print(weight_input_layer1)

print("=====")
print("layer1_layer2_weight")
print(weight_layer1_layer2)

after result : 
 [[0.6021827 ]
 [0.79515023]
 [0.50144091]]
input_layer1_weight
[[ 0.80875052  0.28986117  0.31888935]
 [ 0.39875476  0.82208386  0.3766709 ]
 [-0.49410219  0.43398865  0.07190917]]
=====
layer1_layer2_weight
[[-0.00414515  0.43946714  0.28888699]
 [ 0.90892578  0.766777    0.41005858]
 [ 0.16194871 -0.44372749  0.45222598]]
