In [1]:
import numpy as np

np.random.rand(shape)


=> 행렬 랜덤 변수로 채워 생성

In [4]:
matrix_3_3 = np.random.rand(3,3)
print("matrix Shape : ", matrix_3_3.shape)
print(matrix_3_3)


matrix Shape :  (3, 3)
[[0.26090604 0.09212216 0.80508061]
 [0.59838185 0.25165311 0.91833975]
 [0.19790765 0.96537042 0.33494673]]


In [5]:
matrix_3_1 = np.random.rand(3, 1)
print("matrix Shape : ", matrix_3_1.shape)
print(matrix_3_1)

matrix Shape :  (3, 1)
[[0.62625623]
 [0.60455572]
 [0.69787594]]


전치행렬 (Matrix Transpose)


  np.asarray(배열) => 배열을 행렬로 변환시킴
  
  행렬.T => 전치행렬 변환


In [7]:
matrix_3_1_T = matrix_3_1.T
print(matrix_3_1_T)

[[0.62625623 0.60455572 0.69787594]]


행렬 곱

np.dot(행렬1, 행렬2)

In [8]:
matrix_dot = np.dot(matrix_3_3, matrix_3_1)
print(matrix_dot)

[[0.7809334 ]
 [1.16776591]
 [0.94131238]]


행렬 계산을 통해 간단한 신경망 Skeleton 구현

In [10]:
input = np.asarray([0.9, 0.1, 0.8]) # 인풋 배열을 받아 행렬로 바꿈
weight_input_layer1 = np.asarray(
    [
        [0.9, 0.2, 0.1],
        [0.3, 0.8, 0.5],
        [0.4, 0.2, 0.6]
    ]
)
print(weight_input_layer1)
print("============")

weight_layer1_layer2 = np.asarray([
    [0.3, 0.6, 0.8],
    [0.7, 0.5, 0.1],
    [0.5, 0.2, 0.9]

])

print(weight_layer1_layer2)

[[0.9 0.2 0.1]
 [0.3 0.8 0.5]
 [0.4 0.2 0.6]]
[[0.3 0.6 0.8]
 [0.7 0.5 0.1]
 [0.5 0.2 0.9]]


In [11]:
input_layer1 = np.dot(input, weight_input_layer1)
print(input_layer1)

[1.16 0.42 0.62]


시그모이드 함수를 통해 값 변환

In [12]:
import scipy.special
sigmoid_function = lambda x : scipy.special.expit(x)

input_layer1_sig = sigmoid_function(input_layer1)
print(input_layer1_sig)

[0.76133271 0.60348325 0.65021855]


변환한 값을 인풋 변수로 사용

In [14]:
layer1_layer2 = np.dot(input_layer1_sig, weight_layer1_layer2)
print(layer1_layer2)

print("=======")
layer1_layer2_sig = sigmoid_function(layer1_layer2)
print(layer1_layer2_sig)

[0.97594736 0.88858496 1.25461119]
[0.72630335 0.70859807 0.77809706]
